  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ruby_gems_bootcamp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
